e_com/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

myapp/urls.py
from django.urls import path
from .views import index, product_detail

app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('product/<int:product_id>/', product_detail, name='product_detail'),
]

myapp/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=250)
    price = models.DecimalField(default=0.00, max_digits=7, decimal_places=2)
    description = models.TextField(blank=True)
    
    class Meta:
        db_table = 'products'
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    def __str__(self):
        return self.name
    

myapp/views.py
from django.shortcuts import render
from .models import Product


def index(request):
    products = Product.objects.all()
    context = {
        'title': 'Main Page',
        'products': products
    }
   
    return render(request, 'myapp/index.html', context=context)


def product_detail(request, product_id):
    product = Product.objects.get(id=product_id)
    context = {
        'title': product.name,
        'product': product,
    }
    return render(request, 'myapp/product_detail.html', context=context)

myapp/templates/myapp/contacts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
    <h1>Contacts</h1>
</body>
</html>

myapp/templates/myapp/index.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    {% for product in products %}
        <a href="{% url 'main:product_detail' product.id %}">Подробно о товаре</a>
        <h3>{{ product.name }}</h3>
        <p>{{ product.price }}</p>
        <p>{{ product.description }}</p>
        <br>
    {% endfor %}
{% endblock %}

myapp/templates/myapp/product_detail.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    {{ product.name }}
    <br>
    {{ product.price }}
    <br>
    {{ product.description }}
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="{% static "css/styles.css" %}">

    <title>{{ title }}</title>
</head>

<body class="bg-sky-600">
    {% block content %}{% endblock %}
</body>

</html>